name: primal
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - cython
  - numpy<2
  - setuptools
  - wheel
  - matplotlib
  - tk
  - pip:
      - gym==0.17.0
      - protobuf<5
      - tensorflow[and-cuda]>=2.16,<2.17
      - tf-keras>=2.16,<2.17
      - tqdm==4.67.1
      - tf-slim==1.1.0
